MODEL:
  META_ARCHITECTURE: "RetinaNet"
  BACKBONE:
    NAME: "build_retinanet_resnet_fpn_backbone"
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res3", "res4", "res5"]
  WEIGHTS: "pretrain_weights/model_final_5bd44e.pkl"
  ANCHOR_GENERATOR:
    SIZES: !!python/object/apply:eval ["[[x, x * 2**(1.0/3), x * 2**(2.0/3) ] for x in [64, 128, 256, 512, 1024 ]]"]
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
  RETINANET:
    IOU_THRESHOLDS: [0.4, 0.5]
    IOU_LABELS: [0, -1, 1]
    SMOOTH_L1_LOSS_BETA: 0.0
    NUM_CLASSES: 1
DATASETS:
  TRAIN: ("bill_card_train",)
  TEST: ("bill_card_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01  # Note that RetinaNet uses a different default learning rate
  STEPS: (2000, 4000)
  MAX_ITER: 6000
  CHECKPOINT_PERIOD: 500
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  RANDOM_FLIP: none
  RANDOM_ROTATION_3D:
    ENABLED: True
  RANDOM_Margin_CROP:
    ENABLED: True
  RANDOM_COLOR_JITTER:
    ENABLED: True
TEST:
  EVAL_PERIOD: 100000000
VERSION: 2
